### ISSUE TITLE
No build source

### ISSUE THREAD

**Issue by dronShepherd** [darekf77/ng2-logger#1]
Hi,

nice feature but I'm not able to include it into my project as angular module because after npm install (no js sources) have to include it into my source folder to compile and use

or im doing something wrong :)

Regards
Andrej

**Comment by darekf77** [comment]
Hi,
in my project I am using this repo with [angular 2 webpack starter](https://github.com/AngularClass/angular2-webpack-starter) . It works perfect with webpack... which is looking for ts files. Also I don't need to compile ts to js, webpack will do that for me.

**Comment by darekf77** [comment]
OK from version 0.1.15 there are js files and support for js6 project like this https://github.com/davezuko/react-redux-starter-kit

**Comment by farantesrodrigues** [comment]
I get this error using webpack :

```
ERROR in ./~/ng2-logger/ng2-logger.ts
Module build failed: Error: Typescript emitted no output for <path to project>/node_modules/ng2-logger/ng2-logger.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at Object.loader (/Users/fran/ws/orbit/client/node_modules/ts-loader/dist/index.js:33:15)
 @ ./app/main.ts 7:19-51

```
