### ISSUE TITLE
Fixed width for labels

### ISSUE THREAD

**Issue by m1sh2** [darekf77/ng2-logger#12]
Hello Dariusz,

I'm using your logger on the third project already, it is awesome, thank you.
I made a little enhancement for better usability (screenshot), fixed width for labels:

![image](https://cloud.githubusercontent.com/assets/4172326/22600730/7766b4ec-ea44-11e6-8990-e6be353a3fba.png)

Pretty simple configuration:

```
import { Log, Level } from 'ng2-logger/ng2-logger'
const log = Log.create('AppCmp')
log.color = 'orange'
log.fixedWidth = 30 // width of the label (amount of chars, spaces)
```

Ping me if you'll be interested in the code, I can make a pull request.

**Comment by darekf77** [comment]
Oh oh nice idea:) 

ok, please create pull request if you could...

Thanks for being creative!
