### ISSUE TITLE
Manual import of Log class

### ISSUE THREAD

**Issue by alfupe** [darekf77/ng2-logger#18]
Hi,

I don't know if this is an issue at all. Sorry if not.

Every time I use the Log class, i.e. `Log.create('Component');` I need to manually import it: `import { Log } from 'ng2-logger/ng2-logger';`. I don't understand the reason why my IDE (PhpStorm) cannot autoimport this class as it does with all the other classes, components, models, services, etc.

Thanks!

**Comment by darekf77** [comment]
Hi @alfupe, 
I will try to fix it in new version...

**Comment by alfupe** [comment]
Cool! Thank you!

**Comment by codedoge** [comment]
This is probably because the module is missing the index.d.ts, where the ts definitions are usually found, so you need to provide the filename where the definitions are.

**Comment by darekf77** [comment]
In new version should be in index.d.ts  and also import is like this now:
 ` import { Log } from 'ng2-logger'`
