### ISSUE TITLE
Wrong colors for info and error

### ISSUE THREAD

**Issue by ArturoRis** [darekf77/ng2-logger#20]
I have noted that the border's color when I log info and error are inverted:
 - info has a red border,
 - error has a light blue border.

I have checked the source and there is something strange. The logger.ts file has everything ok whereas the logger.js one has the logger level inverted for the functions "i" and "e".
Can you check as well and correct please ?

**Comment by darekf77** [comment]
ok I will have a look on that

**Comment by ArturoRis** [comment]
Any news about this?

**Comment by darekf77** [comment]
Hi new version will be ready in this week... don't worry @ArturoRis  colors should be fine in new js and ts...
