### ISSUE TITLE
Error when using with Jasmine & Karma 

### ISSUE THREAD

**Issue by niros1** [darekf77/ng2-logger#23]
Hi,
There is an error while using it with Karma:

ERROR in C:/Dev/GitLab/arya/node_modules/ng2-logger/src/log.ts (99,46): Property 'clear' does not exist on type 'Console'.
C:/Dev/GitLab/arya/node_modules/ng2-logger/src/log.ts (100,13): Supplied parameters do not match any signature of call target.
C:/Dev/GitLab/arya/node_modules/ng2-logger/src/log.ts (101,25): Property 'clear' does not exist on type 'Console'.

currently my workaround is to remove setProductionMode method.
Appreciate if you can check the issue / share your thoughts.

Nir.

**Comment by darekf77** [comment]
in nodejs console.clear() does not exist... it is only in the browser. Do not use isProductionMode() with karma/jasmine... try this configuration on production mode for .(karma.conf.js) :  

```
...
    /*
     * level of logging
     * possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
     */
    logLevel: config.LOG_DISABLE
...
```

**Comment by niros1** [comment]
This is a compile time issue.
we fixed it by adding the dom library to the tsconfig.spec.json

"lib": [
      "es2016",
      "dom"
    ],
