### ISSUE TITLE
Injecting as service

### ISSUE THREAD

**Issue by glinkot** [darekf77/ng2-logger#25]
Rather than newing it up, is there a recommended way to pull this in as an injectable service?

Thanks

**Comment by darekf77** [comment]
For now no...  I will do this improvement in ver version.. It's no gonna be as service, but singleton. Thanks for this.

**Comment by glinkot** [comment]
Thanks Darek!  I find the normal console.log often doesn't work when within certain methods, so this is a great addition.  Would be nice just to have a small reference to it in each component rather than doing several steps to bring it in.  Cheers.
