### ISSUE TITLE
ng2-logger and jasmine/karma

### ISSUE THREAD

**Issue by millerf** [darekf77/ng2-logger#26]
I get this weird error in my unit tests:

WARNING in ./node_modules/ng2-logger/src/logger.js
(Emitted value instead of an instance of Error) Cannot find source file 'logger.ts': Error: Can't resolve './logger.ts' in '/XXXXX/node_modules/ng2-logger/src'
 @ ./node_modules/ng2-logger/src/log.js 3:15-34
 @ ./node_modules/ng2-logger/src/index.js
 @ ./node_modules/ng2-logger/index.js
 @ ./src/app/shared/services/AService.service.ts
 @ ./src/test/AService.spec.ts
 @ ./src \.spec\.ts
 @ ./config/karma-shim.js

While it works perfectly in the app, I get this error when testing...
Any idea?

**Comment by millerf** [comment]
After investigating it only happens on the first loaded module...

**Comment by darekf77** [comment]
No this should be problem, in new isomorphic version....
