### ISSUE TITLE
Add Logger to index

### ISSUE THREAD

**Issue by RicardoJBarrios** [darekf77/ng2-logger#28]
Hello.

I'm trying to use ng2-logger (v2.0.26) in a personal library, but each time I try to compile it with Rollup I get this error:

`error TS4029: Public property 'log' of exported class has or is using name 'Logger' from external module "[...]/node_modules/ng2-logger/logger" but cannot be named.`

I tried adding `export * from './logger';` to **index.d.ts** and `__export(require("./logger"));` to **index.js** and it all worked.

Thanks a lot for the library.

**Comment by darekf77** [comment]
Hi Ricardo, thank you very much.
This thing is fixed in new version.

I am super happy that this library is useful for someone...
Have a wonderful day!
