### ISSUE TITLE
fs issue with karma, maybe need to update the document

### ISSUE THREAD

**Issue by xmeng1** [darekf77/ng2-logger#30]
Because ng2-logger **require 'fs'**, and ng test fails Module not found: Error: Can't resolve 'fs' (see this issue https://github.com/angular/angular-cli/issues/8357 and this https://github.com/webpack-contrib/css-loader/issues/447. Maybe need to update the document and let user add configuration to the `karma.conf.js` if the user wants to use karma to test angular.

```
module.exports = function (config) {
  config.set({
    webpack: { node: { fs: 'empty', } },
    basePath: '',
    ......
```

**Comment by darekf77** [comment]
ng2-logger **doesn't require** 'fs' use '**ng2-logger/browser**'

**Comment by jimmykane** [comment]
Getting the same error btw

**Comment by jimmykane** [comment]
@darekf77  nope you are wrong it does https://github.com/darekf77/ng2-logger/blob/3cebe387612d25c48ea5348742672017f89bb4fa/src/backend-logging.ts#L14

**Comment by darekf77** [comment]
@jimmykane check if somewhere in your code you are not refering to **ng2-logger** instead of **ng2-logger/browser**

**Comment by tianchez** [comment]
@darekf77 Got the error after upgrading to Angular 6. I was using `import {Log, Level} from 'ng2-logger'`. After changing to `import {Log, Level} from 'ng2-logger/client'` or `import {Log, Level} from 'ng2-logger/browser'`, `ng serve` is working but not for `ng build`. Do you have any solution?

**Comment by tianchez** [comment]
@jimmykane Is your solution working for you when running `ng build`?

**Comment by jimmykane** [comment]
@tianchez yup. Only import from client

**Comment by tianchez** [comment]
@darekf77 To be specific, I got this error when building with `ng build --prod`
<img width="554" alt="screen shot 2018-05-09 at 4 13 04 pm" src="https://user-images.githubusercontent.com/6414179/39837245-ec012278-53a3-11e8-92e9-773cd6288b16.png">

However, if I build with `ng build --prod --aot=false --build-optimizer=false`, no errors showing up

**Comment by zapphyre** [comment]
I'm using Angular `@angular/core": "^6.0.3` with `@angular/cli": "~6.0.7` and I'm getting:
```
ERROR in ./node_modules/ng2-logger/backend-logging.js
Module not found: Error: Can't resolve 'fs' in '/home/tepo/IdeaProjects/OneDMS-GUI/node_modules/ng2-logger'
ERROR in ./node_modules/ng2-logger/display.js
Module not found: Error: Can't resolve 'path' in '/home/tepo/IdeaProjects/OneDMS-GUI/node_modules/ng2-logger'
ERROR in ./node_modules/ng2-logger/backend-logging.js
Module not found: Error: Can't resolve 'path' in '/home/tepo/IdeaProjects/OneDMS-GUI/node_modules/ng2-logger'
ℹ ｢wdm｣: Failed to compile.
```
when I run `ng serve`
I'm importing from client: `import {Log} from 'ng2-logger/client'`
