### ISSUE TITLE
Reconfiguration after initialization?

### ISSUE THREAD

**Issue by jdoose** [darekf77/ng2-logger#31]
I noticed that the logger cannot be reconfigured after initialization, i.e. `setProductionMode`.

Is this intended and why? Thanks for your feedback!

**Comment by darekf77** [comment]
I think it doesn't make sense to change this value multiple-times during application execution time...

**Comment by jdoose** [comment]
In our use case, we wanted to have a menu button on the website to allow the user to enable/disable logging.
This is currently not possible.
I do not see a technical reason to prevent it or did I miss something?

**Comment by darekf77** [comment]
@jdoose logger from version **2.0.42** should be reconfigurable in production mode.
