### ISSUE TITLE
Coloring log messages in console not working in IE11

### ISSUE THREAD

**Issue by jdoose** [darekf77/ng2-logger#32]
In IE11, the coloring of the console output does not work:
![image](https://user-images.githubusercontent.com/3868618/36776277-829bde42-1c65-11e8-8a81-5abdcfa3e027.png)

It should be possible to fix this by modifying display.ts, line 40-42, right?

**Comment by darekf77** [comment]
https://github.com/darekf77/ng2-logger/issues/29
