### ISSUE TITLE
Feature: Group

### ISSUE THREAD

**Issue by danielsogl** [darekf77/ng2-logger#38]
Following the Console Web Api the group functions are missing

```js
console.log("This is the outer level");
console.group();
console.log("Level 2");
console.group();
console.log("Level 3");
console.warn("More of level 3");
console.groupEnd();
console.log("Back to level 2");
console.groupEnd();
console.log("Back to the outer level");
```

```js
console.groupCollapsed([label]);
console.groupEnd();
```

**Comment by darekf77** [comment]
I would't recommend to group console logs from for anyone....  You can't see what is inside... and probably you should use debugger or more split you code to smaller modules (and apply ng2-logger for each of them).
