### ISSUE TITLE
setProductionMode

### ISSUE THREAD

**Issue by CarstenLeue** [darekf77/ng2-logger#41]
The doc shows this example how to enable selective debugging

    Log.setProductionMode();
    Log.onlyModules('src:books', 'src:records', 'src:page:login');
    Log.onlyLevel(Level.ERROR,Level.INFO);

However it looks as if "setProductionMode" disables the logging altogether, even if levels or modules are enabled afterwards. Is this as intended?

**Comment by darekf77** [comment]
I always set  `Level.__NOTHING` for each component which is done. If you have lots of modules/components/files with  `Level.__NOTHING` you may be try to log only specific modules with `Log.onlyModules('src:books', 'src:records', 'src:page:login');`.

**Comment by CarstenLeue** [comment]
@darekf77 does this mean that Log.setProductionMode(); is only supposed to be used if no logging is desired at all?

**Comment by darekf77** [comment]
yes...
