### ISSUE TITLE
Log levels are optimized away in ng6 build

### ISSUE THREAD

**Issue by CarstenLeue** [darekf77/ng2-logger#44]
I noticed that when using this library in an Angular 6 project, this code:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Level;
(function (Level) {
    Level[Level["DATA"] = 0] = "DATA";
    Level[Level["INFO"] = 1] = "INFO";
    Level[Level["WARN"] = 2] = "WARN";
    Level[Level["ERROR"] = 3] = "ERROR";
    Level[Level["__NOTHING"] = 4] = "__NOTHING";
})(Level = exports.Level || (exports.Level = {}));
//# sourceMappingURL=level.js.map
```
is NOT part of my application bundle, the optimizer seems to remove it as a side effect (https://github.com/webpack/webpack/tree/master/examples/side-effects).

Would it be possible to provide a side effects free bundle (see webpack v4 "sideEffects": false in webpack https://goo.gl/jB3GVv).

It might be as simple as recompiling the bundle with ng-packagr using the latest libraries.

**Comment by darekf77** [comment]
@CarstenLeue  is this still as issue ?

**Comment by darekf77** [comment]
on angular 7 everything works smooth...

**Comment by CarstenLeue** [comment]
looks good, thanks
