### ISSUE TITLE
Ng serve failed on ng2-logger version 2.0.38 with Angular 7

### ISSUE THREAD

**Issue by dlxu** [darekf77/ng2-logger#47]
Ng serve failed with following message
```
ERROR in ./node_modules/ng2-logger/backend-logging.js
Module not found: Error: Can't resolve 'fs' in '/tmp/prod-stockholm/node_modules/ng2-logger'
ERROR in ./node_modules/ng2-logger/display.js
Module not found: Error: Can't resolve 'path' in '/tmp/prod-stockholm/node_modules/ng2-logger'
ERROR in ./node_modules/ng2-logger/backend-logging.js
Module not found: Error: Can't resolve 'path' in '/tmp/prod-stockholm/node_modules/ng2-logger'
ℹ ｢wdm｣: Failed to compile.

```

I am importing `ng2-logger/client` and also tried `ng2-logger/browser`

**Comment by billdwhite** [comment]
same issue here

**Comment by dlxu** [comment]
It was working yesterday. Today is Dec 4, 2018, EST. Is there anything happen to `tnp` @darekf77

**Comment by darekf77** [comment]
ok fixed now

**Comment by nhustak** [comment]
I just updated my Angular 7 app from ng2-logger: 2.0.35 to 2.0.44 and this issues has re-appeared.   I had also updated several other libraries, so I reverted logger to 2.0.35 to make sure and now Angular builds.   Definitely a problem.

Module not found: Error: Can't resolve 'fs' in 'C:\ProjDotNet\collegebowl-site\node_modules\ng2-logger'
ERROR in ./node_modules/ng2-logger/display.js

"@angular/animations": "^7.1.4",
"@angular/common": "^7.1.4",
"@angular/compiler": "^7.1.4",
"@angular/core": "^7.1.4",
"@angular/forms": "^7.1.4",
"@angular/http": "^7.1.4",
"@angular/platform-browser": "^7.1.4",
"@angular/platform-browser-dynamic": "^7.1.4",
"@angular/router": "^7.1.4",
"bootstrap": "^4.1.3",
"core-js": "^2.6.1",
"devextreme": "^18.2.4",
"devextreme-angular": "18.2.4",
"moment": "^2.23.0",
"ng2-logger": "^2.0.44",
"ngx-cookie-service": "^2.1.0",
"ngx-spinner": "^6.0.0",
"roboto-fontface": "^0.10.0",
"rxjs": "^6.3.3",
"stream": "0.0.2",
"tslib": "^1.9.0",
"zone.js": "^0.8.26"

**Comment by darekf77** [comment]
@nhustak try to use **ng2-logger/browser** instead of alone **ng2-logger**.  Import of backend version **ng2-logger** cause the issue....

**Comment by darekf77** [comment]
make sure that you **don't have** alone import of **ng2-logger** in your angluar ( or whatever client ) code....

**Comment by nhustak** [comment]
@darekf77   Ah I wasn't aware that was an issue.  I will look.  Thank you!
