### ISSUE TITLE
ng2-logger not working in lazy loading sub-module IE 11 (Angular8)

### ISSUE THREAD

**Issue by kliarist** [darekf77/ng2-logger#49]
We are using ` "ng2-logger": "~3.0.11"` and while it seems to be working fine for all browsers and submodules (Angular lazy loading) it wont work in IE11 and in particular for lazy loaded modules (it works for top level modules). Attached is the exception.  Do you happen to have any idea what might be wrong ? 
![image](https://user-images.githubusercontent.com/1371419/73187247-cc94f480-4129-11ea-8ef4-753e12a9484e.png)

**Comment by darekf77** [comment]
@kliarist I am currently testing and rewriting my libraries to be compatible with new angular 9. 

By reading your browser errors log I am not sure what exactly happen.. but try to import **es5** version or downgrade ng2-logger to version 2.x.x. 

- to use es5 version and version 3.x.x change imports to : 
```
import { Log, Level } from 'ng2-logger/browser/es5'

```

 - to use old version in your **package.json** change:
```
"ng2-logger": "^2.0.48"
```

**Comment by kliarist** [comment]
I ended up using `"ng2-logger": "~3.0.11",` and importing

`import { Log, Level } from 'ng2-logger/browser/es5'` as advised. It seems to be working fine with IE11

Many thanks!
