### ISSUE TITLE
Warnings from ng9 build

### ISSUE THREAD

**Issue by CarstenLeue** [darekf77/ng2-logger#50]
When pulling in the browser version of `ng2-logger`  in an ng9 ivy build I get this warning:

```
WARNING in Entry point '@acoustic-content-sdk/ng-logger' contains deep imports into '/usr/build/sites/node_modules/ng2-logger/browser'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

I think this is because `ng2-logger/browser` does not contain its own `package.json` file. Could you consider representing `ng2-logger/browser` using a secondary entry point instead of having to use deep imports? 

https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md

**Comment by darekf77** [comment]
( Sorry for delay ) Sure... in next version there will be package .json for /browser.

**Comment by darekf77** [comment]
Now... from version 3.0.12 there is **package.json** in _browser_ or _client_ folder.
