### ISSUE TITLE
npm install moderate vulnerability

### ISSUE THREAD

**Issue by mikeandtherest** [darekf77/ng2-logger#58]
Hi there. On a new Angular 13.03 project, I'm getting one moderate vulnerability at npm install, which seems to be caused by an indirect dependency of ng2-logger (i.e. sync-exec). I'm not sure how easy it would be to address it, but I just wanted to make you guys aware of it.

Btw, I'm using this version of the library: `"ng2-logger": "^8.0.20"`.

Npm audit output:

```js
  Moderate        Tmp files readable by other users in sync-exec                

  Package         sync-exec                                                     

  Patched in      No patch available                                            

  Dependency of   ng2-logger                                                    

  Path            ng2-logger > tnp-cli > tnp-config > tnp-core > copy-paste >   
                  sync-exec                                                     

  More info       https://github.com/advisories/GHSA-38h8-x697-gh8q      

found 1 moderate severity vulnerability in 1422 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

**Comment by darekf77** [comment]
Hi @mikeandtherest ...let me check that today.

**Comment by darekf77** [comment]
@mikeandtherest use new version and don't forget to use
`
import { Log, Logger } from 'ng2-rest/browser'; 
`
Browser version does not use sync-exec and you should be safe.
